# Generated by Django 3.1 on 2020-10-21 02:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='like',
        ),
        migrations.AddField(
            model_name='comments',
            name='like',
            field=models.ManyToManyField(related_name='likes_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='likes_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
