# Generated by Django 3.1 on 2020-10-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20201026_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='refered_post',
        ),
    ]
