# Generated by Django 3.1 on 2020-10-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20201026_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='refered_post',
            new_name='posts',
        ),
    ]
