# Generated by Django 3.1 on 2020-10-27 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20201026_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test1',
            old_name='foreignKey',
            new_name='foreignKeyhi',
        ),
    ]
