# Generated by Django 3.1 on 2020-10-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_auto_20201026_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test1',
            old_name='name',
            new_name='nasdme',
        ),
        migrations.AddField(
            model_name='test1',
            name='dursdfation',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test1',
            name='orsdfder',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test1',
            name='tisdftle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test2',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test2',
            name='order',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test2',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
