# Generated by Django 3.1 on 2020-10-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_album_track'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
