# Generated by Django 3.1 on 2020-10-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_auto_20201027_1020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test1',
        ),
        migrations.DeleteModel(
            name='Test2',
        ),
    ]
