# Generated by Django 3.1 on 2020-10-29 00:53

from django.db import migrations, models
import django.utils.timezone
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_auto_20201028_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=network.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
