# Generated by Django 3.1 on 2020-10-29 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_auto_20201028_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='create_at',
        ),
    ]
