# Generated by Django 3.1 on 2020-10-29 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_auto_20201028_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
