# Generated by Django 3.1 on 2020-10-30 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_auto_20201028_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
