# Generated by Django 3.1 on 2020-10-31 20:31

from django.db import migrations
import django.utils.timezone
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_auto_20201030_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=network.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
