# Generated by Django 3.1 on 2020-11-09 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0030_auto_20201109_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follower',
        ),
        migrations.AddField(
            model_name='user',
            name='follower',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_follower_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
