# Generated by Django 3.1 on 2020-11-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0034_auto_20201111_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/static/3x4.jpg', upload_to='static/'),
        ),
    ]
