# Generated by Django 3.1 on 2020-11-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0035_auto_20201113_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, default='/static/3x4.jpg', upload_to='static/'),
        ),
    ]
