# Generated by Django 3.1 on 2020-11-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0036_auto_20201113_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, default='/static/user.png', upload_to='static/'),
        ),
    ]
